# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ib_common.vernacular_utils.vernacular_utilities_class


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('_contents', models.CharField(max_length=1000)),
                ('_multimedia_url', models.CharField(blank=True, max_length=500, null=True)),
                ('_multimedia_type', models.CharField(blank=True, choices=[(b'IMAGE', b'Image'), (b'VIDEO', b'Video'), (b'AUDIO', b'Audio')], max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('article_id', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
            bases=(models.Model, ib_common.vernacular_utils.vernacular_utilities_class.VernacularUtilitiesClass),
        ),
        migrations.CreateModel(
            name='PostVernacularDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('language_name', models.CharField(default=b'ENGLISH', max_length=100)),
                ('v_contents', models.CharField(max_length=500)),
                ('v_multimedia_url', models.CharField(blank=True, max_length=500, null=True)),
                ('v_multimedia_type', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vernacular_details', to='ib_posts.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postvernaculardetails',
            unique_together=set([('post', 'language_name')]),
        ),
    ]
