# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvernaculardetails',
            name='v_multimedia_type',
            field=models.CharField(blank=True, choices=[(b'IMAGE', b'Image'), (b'VIDEO', b'Video'), (b'AUDIO', b'Audio')], max_length=200, null=True),
        ),
    ]
