# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0002_memberrelation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrelation',
            name='status',
            field=models.CharField(choices=[(b'ACCEPT', b'Accept'), (b'PENDING', b'Pending'), (b'REJECT', b'Reject')], default=b'PENDING', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='memberrelation',
            unique_together=set([('m_id', 'm_type', 'r_m_id', 'r_m_type', 'relation')]),
        ),
    ]
