# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0003_auto_20170427_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberrelation',
            unique_together=set([]),
        ),
    ]
