# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0004_auto_20170606_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrelation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='m_social_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='memberrelation',
            unique_together=set([('m_id', 'm_type', 'r_m_id', 'r_m_type', 'relation')]),
        ),
    ]
