# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0005_auto_20170616_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrelation',
            name='status',
            field=models.CharField(choices=[(b'ACCEPT', b'Accept'), (b'PENDING', b'Pending'), (b'WAITING_FOR_APPROVAL', b'Waiting for Approval'), (b'REJECT', b'Reject')], default=b'PENDING', max_length=100),
        ),
    ]
