# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0006_auto_20170627_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrelation',
            name='status',
            field=models.CharField(choices=[(b'ACCEPT', b'Accept'), (b'PENDING', b'Pending'), (b'WAITING_FOR_APPROVAL', b'Waiting for Approval'), (b'REJECT', b'Reject')], default=b'ACCEPT', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='memberrelation',
            unique_together=set([]),
        ),
    ]
