# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_social', '0007_auto_20170629_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrelation',
            name='source',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='relation',
            field=models.CharField(choices=[(b'FRIEND', b'Friend'), (b'FB_FRIEND', b'Facebook Friend'), (b'FOLLOW', b'Following'), (b'BLOCK', b'Block')], default=b'FRIEND', max_length=255),
        ),
    ]
