# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibuser',
            name='language',
            field=models.CharField(choices=[(b'ENGLISH', b'ENGLISH'), (b'HINDI', b'HINDI'), (b'TAMIL', b'TAMIL'), (b'TELUGU', b'TELUGU')], default=b'ENGLISH', max_length=100, null=True),
        ),
    ]
