# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0002_auto_20170405_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ibuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
