# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0004_auto_20170406_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('otp_token', models.CharField(max_length=8)),
                ('auth_type', models.CharField(default=b'phone_number', max_length=15)),
                ('expiry_time', models.BigIntegerField()),
                ('reset_count', models.IntegerField(default=1)),
                ('ib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='changehistory',
            name='type',
            field=models.CharField(choices=[(b'email', b'Email'), (b'phone_number', b'Phone Number'), (b'password', b'Password'), (b'username', b'Username'), (b'none', b'None')], default=b'NONE', max_length=10),
        ),
    ]
