# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0006_auto_20170408_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, choices=[(b'facebook', b'Facebook'), (b'twitter', b'Twitter'), (b'google', b'Google')], max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Social Provider',
            },
        ),
        migrations.CreateModel(
            name='UserSocialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('social_tokens', models.CharField(default=b'', max_length=100)),
                ('extra_info', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name': 'User Social Provider',
            },
        ),
        migrations.AddField(
            model_name='ibuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='changehistory',
            name='type',
            field=models.CharField(choices=[(b'email', b'Email'), (b'phone_number', b'Phone Number'), (b'password', b'Password'), (b'username', b'Username'), (b'session', b'Session'), (b'none', b'None')], default=b'NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='usersocialprovider',
            name='ib_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_user_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersocialprovider',
            name='social_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_provider_key', to='ib_users.SocialProvider'),
        ),
        migrations.AddField(
            model_name='ibuser',
            name='social_provider',
            field=models.ManyToManyField(related_name='social_provider_user', through='ib_users.UserSocialProvider', to='ib_users.SocialProvider'),
        ),
    ]
