# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0007_auto_20170410_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialprovider',
            old_name='social_tokens',
            new_name='social_token',
        ),
        migrations.AlterField(
            model_name='changehistory',
            name='type',
            field=models.CharField(choices=[(b'email', b'Email'), (b'phone_number', b'Phone Number'), (b'password', b'Password'), (b'username', b'Username'), (b'session', b'Session'), (b'activation', b'Activation'), (b'deletion', b'Deletion'), (b'none', b'None')], default=b'NONE', max_length=10),
        ),
    ]
