# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0009_auto_20170416_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialprovider',
            name='extra_info',
            field=models.CharField(default=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usersocialprovider',
            name='social_token',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
