# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0010_auto_20170422_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_token',
            field=models.CharField(max_length=128),
        ),
    ]
