# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0011_auto_20170423_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default=b'', max_length=25)),
                ('ud_key', models.CharField(default=b'', max_length=25)),
                ('ud_value', models.CharField(max_length=500)),
                ('ib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Extra Data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userextradata',
            unique_together=set([('ib_user', 'source', 'ud_key')]),
        ),
    ]
