# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0012_auto_20170424_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='auth_type',
            field=models.CharField(default=b'phone_number', max_length=100),
        ),
    ]
