# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0013_auto_20170505_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='type',
            field=models.CharField(choices=[(b'email', b'Email'), (b'phone_number', b'Phone Number'), (b'password', b'Password'), (b'username', b'Username'), (b'session', b'Session'), (b'activation', b'Activation'), (b'deletion', b'Deletion'), (b'none', b'None')], default=b'NONE', max_length=100),
        ),
    ]
