# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0014_auto_20170506_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialprovider',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
