# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0015_usersocialprovider_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprovider',
            name='name',
            field=models.CharField(blank=True, choices=[(b'facebook', b'Facebook'), (b'twitter', b'Twitter'), (b'google', b'Google'), (b'linkedin', b'LinkedIn')], max_length=15, null=True),
        ),
    ]
