# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0018_auto_20170912_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibuser',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ibuser',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
