# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_users', '0019_auto_20171014_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='changehistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
