# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('entity_id', models.IntegerField()),
                ('entity_type', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[(b'RATE', b'RATE'), (b'LIKE', b'LIKE'), (b'VOTE', b'VOTE'), (b'LOVE', b'LOVE'), (b'SHARE', b'SHARE'), (b'FOLLOW', b'FOLLOW'), (b'BOOKMARK', b'BOOKMARK'), (b'FAVOURITE', b'FAVOURITE'), (b'SUBSCRIBE', b'SUBSCRIBE'), (b'ATTEND', b'ATTEND')], max_length=30)),
                ('action_value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('entity_id', 'entity_type', 'user_id', 'source', 'action_type')]),
        ),
    ]
