# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_action', '0002_auto_20170422_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[(b'RATE', b'RATE'), (b'LIKE', b'LIKE'), (b'VOTE', b'VOTE'), (b'LOVE', b'LOVE'), (b'SHARE', b'SHARE'), (b'FOLLOW', b'FOLLOW'), (b'BOOKMARK', b'BOOKMARK'), (b'BOOK_STATUS', b'BOOK_STATUS'), (b'BOOK_PROGRESS', b'BOOK_PROGRESS'), (b'FAVOURITE', b'FAVOURITE'), (b'SUBSCRIBE', b'SUBSCRIBE'), (b'REPORT', b'REPORT'), (b'HELPFUL', b'HELPFUL'), (b'ATTEND', b'ATTEND'), (b'SAVE_STATUS', b'SAVE_STATUS')], max_length=30),
        ),
    ]
