# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_action', '0002_auto_20170422_1438'),
        ('ib_action', '0003_auto_20170421_1115'),
    ]

    operations = [
    ]
