# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_action', '0003_auto_20170612_2014'),
        ('ib_action', '0004_merge_20170423_1258'),
    ]

    operations = [
    ]
