# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('extra_data', models.TextField(blank=True, max_length=1000000000, null=True)),
                ('title', models.CharField(default=b'iBHubs', max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=30)),
                ('default', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default=b'ON', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100)),
                ('read_status', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('device_ids', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCMToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cm_type', models.CharField(choices=[('FCM', 'FCM'), ('ONESIGNAL', 'ONESIGNAL'), ('PUBNUB', 'PUBNUB')], default=b'FCM', max_length=10)),
                ('cm_token', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_choice_id', models.IntegerField()),
                ('preference', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default=b'ON', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationchoice',
            unique_together=set([('source', 'name')]),
        ),
        migrations.AddField(
            model_name='notification',
            name='members',
            field=models.ManyToManyField(to='ib_notifications.NotificationReceiver'),
        ),
    ]
