# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='service',
            new_name='cm_type',
        ),
        migrations.RenameField(
            model_name='notificationreceiver',
            old_name='device_ids',
            new_name='cm_token',
        ),
        migrations.AlterField(
            model_name='usercmtoken',
            name='cm_type',
            field=models.CharField(choices=[('FCM', 'FCM'), ('ONESIGNAL', 'ONESIGNAL'), ('PUBNUB', 'PUBNUB'), ('SOCKET', 'SOCKET')], max_length=10),
        ),
    ]
