# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0003_notificationreceiver_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
