# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0004_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=50, null=True)),
                ('group_type', models.CharField(choices=[('GENERAL', 'GENERAL')], default=b'GENERAL', max_length=50)),
                ('source', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(default=-1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='ib_notifications.NotificationGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroupmember',
            unique_together=set([('group', 'user_id')]),
        ),
    ]
