# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0005_auto_20170626_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchoice',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationchoice',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercmtoken',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercmtoken',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usernotificationchoice',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotificationchoice',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
