# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0006_auto_20170627_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationchoice',
            old_name='default',
            new_name='default_option',
        ),
    ]
