# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0007_auto_20170630_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationchoice',
            old_name='default_option',
            new_name='default_choice',
        ),
    ]
