# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0008_auto_20170630_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgroup',
            name='entity_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='entity_type',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='source',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroup',
            unique_together=set([('entity_id', 'entity_type', 'source')]),
        ),
    ]
