# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ib_notifications', '0009_auto_20170710_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercmtoken',
            name='device_id',
            field=models.TextField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercmtoken',
            name='device_type',
            field=models.TextField(default=b'ANDROID'),
        ),
        migrations.AddField(
            model_name='usercmtoken',
            name='status',
            field=models.CharField(default=b'ACTIVE', max_length=200),
        ),
    ]
