SIPTHOR_ACTION_SOURCE = "phd3"
SIPTHOR_ACTION_ARTICLES = "articles"
SIPTHOR_ACTION_POSTS = "posts"
SIPTHOR_ACTION_BOOKMARK = "BOOKMARK"
SIPTHOR_ACTION_LIKE = "LIKE"
SIPTHOR_ACTION_DISLIKE = "DISLIKE"
SIPTHOR_ACTION_SHARE = "SHARE"
SIPTHOR_ACTION_NEUTRAL = "NEUTRAL"



IB_SOCIAL_USER_TYPE = "USER"
IB_SOCIAL_FOLLOW_TYPE = "FOLLOW"
IB_SOCIAL_FOLLOWING_TYPE = "FOLLOWING"

RELATED_RELATIONS = {
    IB_SOCIAL_FOLLOW_TYPE : IB_SOCIAL_FOLLOWING_TYPE
}



