# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ib_common.vernacular_utils.vernacular_utilities_class


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('_title', models.CharField(max_length=500)),
                ('_url', models.CharField(max_length=255)),
                ('_summary', models.TextField(max_length=100000000)),
                ('_author_name', models.CharField(max_length=100)),
                ('_published_time', models.DateTimeField(null=True)),
                ('_tags', models.TextField(blank=True, max_length=1000, null=True)),
                ('_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_keywords_added', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-_published_time'],
            },
            bases=(models.Model, ib_common.vernacular_utils.vernacular_utilities_class.VernacularUtilitiesClass),
        ),
        migrations.CreateModel(
            name='ArticleKeywordMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVernacularDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('language_name', models.CharField(default=b'ENGLISH', max_length=100)),
                ('v_title', models.CharField(max_length=500)),
                ('v_url', models.CharField(max_length=255)),
                ('v_summary', models.TextField(max_length=100000000)),
                ('v_author_name', models.CharField(max_length=100)),
                ('v_published_time', models.DateTimeField(null=True)),
                ('v_tags', models.TextField(blank=True, max_length=1000, null=True)),
                ('v_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vernacular_details', to='ib_articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('_keyword', models.CharField(max_length=100)),
            ],
            bases=(models.Model, ib_common.vernacular_utils.vernacular_utilities_class.VernacularUtilitiesClass),
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('sub_group', models.CharField(blank=True, max_length=100, null=True)),
                ('group_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordVernacularDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('language_name', models.CharField(default=b'ENGLISH', max_length=100)),
                ('v_keyword', models.CharField(max_length=100)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vernacular_details', to='ib_articles.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserSuggestedNewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_articles.NewsSource')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_articles.KeywordGroup'),
        ),
        migrations.AddField(
            model_name='articlekeywordmap',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ib_articles.Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_articles.Cluster'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', through='ib_articles.ArticleKeywordMap', to='ib_articles.Keyword'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ib_articles.NewsSource'),
        ),
        migrations.AlterUniqueTogether(
            name='usersuggestednewssource',
            unique_together=set([('user_id', 'news_source')]),
        ),
        migrations.AlterUniqueTogether(
            name='keywordvernaculardetails',
            unique_together=set([('keyword', 'language_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('keyword_group', '_keyword')]),
        ),
        migrations.AlterUniqueTogether(
            name='articlevernaculardetails',
            unique_together=set([('article', 'language_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='articlekeywordmap',
            unique_together=set([('article', 'keyword')]),
        ),
    ]
