# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='unique_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
