# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_articles', '0002_keyword_unique_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordgroup',
            name='group',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='keywordgroup',
            name='sub_group',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
