# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_articles', '0004_auto_20170702_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='_keyword',
            field=models.CharField(max_length=300),
        ),
    ]
