# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_articles', '0005_auto_20170702_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordvernaculardetails',
            name='v_keyword',
            field=models.CharField(max_length=300),
        ),
    ]
